<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>LMLocal.Tests.E2E.VSIX</RootNamespace>
    <VSTestHostRootSuffix>Exp</VSTestHostRootSuffix>
    <CopyVsixToTestDirectory>true</CopyVsixToTestDirectory>
    <IsTestProject>true</IsTestProject>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LMLocal\LMLocal.csproj" Condition="Exists('..\LMLocal\LMLocal.csproj')" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.1.0" />
    <PackageReference Include="MSTest.TestFramework" Version="4.1.0" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" Version="17.14.2120" PrivateAssets="all" />
  </ItemGroup>
</Project>
